### ISSUE TITLE
Mesh ID regex not catching all the values

### ISSUE THREAD

**Issue by rafspiny** [MrMimic/MEDOC#13]
There are Mesh IDs with more than 7 digits in it.
For the sake of completeness of the DB I made sure to capture all the possible IDs with: 

```python
'descriptor_ui': re.findall( '<descriptorname .*?ui="(D\d+)".*?>.*?</descriptorname>', str(mesh)),
'qualifier_ui': re.findall('<qualifiername .*?ui="(Q\d+)">.*?</qualifiername>', str(mesh)),
```
Example: D000074606 for term **Smoking prevention**

**Comment by dhimmel** [comment]
Some references with slightly more specific regexes (in case it matters for your application):

- https://registry.identifiers.org/registry/mesh
- https://www.wikidata.org/wiki/Property:P486.
- https://id.nlm.nih.gov/mesh/describe?uri=http%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23identifier

    > A property of Descriptors, Qualifiers, SupplementaryConceptRecords, Concepts and Terms. Descriptor identifier is a 7 or 10 alphanumeric starting with the letter D. Qualifier identifier is a 7 or 10 alphanumeric starting with the letter Q. SupplementaryConceptRecord identifier is a 7 or 10 alphanumeric starting with the letter C. Concept identifier is an 8 or 10 alphanumeric starting with the letter M. Term identifier is a 7 or 10 alphanumeric starting with the letter T. The 10 alphanumeric format was implemented for new identifiers created on or after about May 19, 2014.
