### ISSUE TITLE
Incomplete database

### ISSUE THREAD

**Issue by helmersl** [MrMimic/MEDOC#17]
I have the problem that pubmed_citations contains only ~19000000 articles instead of ~26000000. Also some of the PMIDs are wrong. Is there a possibility to fetch only the missing documents?

**Comment by MrMimic** [comment]
Hi. Some articles are not returned through the NCBI API. 
Anyway, I'll check to add an option trying to complete the insertion in case of trouble.

**Comment by MrMimic** [comment]
I just tried, I got 25M more or less. Think this is alright now.
