### ISSUE TITLE
Processing getting stuck for hours

### ISSUE THREAD

**Issue by nikolamilosevic86** [MrMimic/MEDOC#18]
Hello, 

I have started running the script and it managed to create a database and insert about 120k citations into medline_citation, however, then it gets stuck for hours without any output or inserting anything into database. The output only states: 
INFO:root:Processing file baseline/pubmed20n0677.xml.gz.
INFO:root:Downloading file baseline/pubmed20n0677.xml.gz (0.14 min)

I have removed most/all of the indexes, but it does not seem it is a problem with inserts. Any ideas what is going on here after a while?

**Comment by MrMimic** [comment]
Hi, sorry for delayed answer.

I have no idea .. Maybe an encoding problem. 

Or did you changes something in the SQL configuration of the host ?

**Comment by MrMimic** [comment]
I suppose it is now solved.
