### ISSUE TITLE
Other sources and IDs not parsed correctly

### ISSUE THREAD

**Issue by rafspiny** [MrMimic/MEDOC#5]
In the table `medline_citation_other_id` I can see rows where the `source` fields has the following value:
**NLM>PMC1864552</otherid>\n<otherid source=PIP>011001</otherid>\n<otherid source=POP**

This is the original XML file: https://www.ncbi.nlm.nih.gov/pubmed/62366?report=xml&format=text
This is the relevant part of it:
```xml
        <OtherID Source="NLM">PMC1864552</OtherID>
        <OtherID Source="PIP">011001</OtherID>
        <OtherID Source="POP">00113730</OtherID>
```
I suppose that the outcome should be three rows with the same pmid and different `source` and `other_id` fields. But the pmid `field`. It sounds reasonable.

* **NLM** and **PMC1864552**
* **PIP** and **011001** 
* **POP** and **00113730** 

Thanks again for your great work. I am not gonna take a look at this one cause you said that MEDOC is undergoing major development and refactoring ATM, so probably this issue is already on your radar :)

**Comment by MrMimic** [comment]
Hi !
Good point ! I corrected the way other_id are stored and parsed :)
Thanks for your reviews !

**Comment by MrMimic** [comment]
Thanks a lot guy, I know MEDOC need improvment, but ATM I'm really busy by other projects, so I really can't take care of !
GitHub's collaboration are awesome ;)
